blank_issues_enabled: false
contact_links:
  - name: Report a bug
    url: https://github.com/cometchat-pro
    about: Please create a Github issue for the relevant SDK/UI Kit. We do not provide direct support for tutorials.
  - name: Feature Request
    url: https://feedback.cometchat.com/cometchat-pro-feature-requests
    about: Suggest an idea or a feature for this project
  - name: Community Forums
    url: https://forum.cometchat.com
    about: Discuss this in the CometChat Pro Community Forums
  - name: Documentation
    url: https://prodocs.cometchat.com
    about: Read the documentation
